### PR TITLE
refactored liburing support

### LINKED ISSUE #29: improved liburing threading model
See discussion at https://github.com/axboe/liburing/discussions/847.  It is likely that the submission thread is is carrying more CPU burden than expected in the current threading model in #20.

Need to:
a) do some mild profiling and confirm that this is the case.  Probably best to do this on Frontier.
b) assuming confirmation of the CPU utilization hotspot, experiment with alternative models that distribute work over N rings/submitters

### PR DESCRIPTION
**Pull request by carns**
fixes #29

### CODE REVIEW

**Comment by carns** [comment]
A few more things going on here:

- need to validate on Polaris (that new code path works correctly on older kernels and check performance)
- add test cases that exercise liburing build if enabled
- if this is merged, need to add (optional) liburing dependency and variant

**Comment by carns** [comment]
Code is tested and performance validated on three different systems with different kernels (local workstation with latest Ubuntu, Polaris, and Frontier.  After merge, the following will need to be done:

- [ ] tag new release
- [ ] bump spack version and add +liburing variant and optional dependency
- [ ] update github action to also build and test with liburing (this will also likely fix the coverage issues)
- [ ] update RTD documentation to explain how to configure and use liburing

**Review by mdorier — APPROVED** [review]
Looks good to me. The only comment I have is not related to uring: we might want to use `ABT_eventual_memory` and `ABT_mutex_memory` instead of `ABT_eventual` and `ABT_mutex`. We have macros in the margo codebase to select one or the other based on availability. Using the `_memory` version removes an allocation, which can be good for the `abt_io_io_state` structure, which are allocated on each operation.

**Comment by carns** [comment]
Ah, good call on the _memory variants.  I'll open a separate issue to track that.

**Pull request merged**
