### PR TITLE
configure option to omit i/o

### PR DESCRIPTION
**Pull request by roblatham00**
PVFS days taught us it was helpful to be able to assume infinitely fast
storage to suss out any other performance overheads.

### CODE REVIEW

**Comment by carns** [comment]
This is a good idea to put this functionality directly in abt-io in case we can use it in multiple places.

As for the configuration, I think it would be best to avoid adding a field to `abt_io_init_info`, and instead have users rely on the json exclusively to set it (or not).  

The `validate_and_complete_config()`, can make sure it is set to a default value of 0 if not specified.  Then after that function completes, `abt_io_init_ext()` can safely parse it without any additional sanity checking, and put the integer value in a field in the `abt_io_instance` for convenience of subsequent use without touching json again.

Somewhat orthogonal, but I wonder if instead of adding individual arguments to affected `issue_*` functions and fields to affected `_state` structs,  maybe it would be better to pass the `abt_io_instance` (i.e., `aid`) struct in all such functions.  Right now a few of the functions would just check an aid->do_null_io flag, but it would give us a way in the future to pass runtime instance-specific parameters (or maybe performance counters etc.) around to the io routines.

**Comment by roblatham00** [comment]
I think passing `aid` to the functions is a great idea in fact I already did it once!  (in https://github.com/mochi-hpc/mochi-abt-io/pull/8) .   Let me land that bit first

**Comment by roblatham00** [comment]
In latest revision I split out "null read" from "null write" -- I can imagine a few scenarios where we might need the reads to be valid:
- input deck for a simulation
- config file for a benchmark
- HDF5 needs to read metadata before writing

**Comment by carns** [comment]
Looks great!

@roblatham00 are you planning any other changes in this PR or is it good to merge? (just double-checking b/c of the WIP: prefix)

**Comment by roblatham00** [comment]
Let me run a few tests and I'll commit it thanks for the review.

**Comment by roblatham00** [comment]
dropping the WIP.  this is ready to go.  I made some changes to test/basic.c to let me exercise json configs.  I can drop those test changes if you'd prefer.

**Pull request merged**
